// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMSdHHl1JFSx14q-fS5T6blmpDnRunaWw',
    appId: '1:1085267534409:web:a44e217a86e800121b5598',
    messagingSenderId: '1085267534409',
    projectId: 'fir-test-b43d4',
    authDomain: 'fir-test-b43d4.firebaseapp.com',
    storageBucket: 'fir-test-b43d4.appspot.com',
    measurementId: 'G-4BYB9KKCZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcFYL8vjlcdr75GRTanHiud8e5GIFQde0',
    appId: '1:1085267534409:android:1c97a5d6cc8da3521b5598',
    messagingSenderId: '1085267534409',
    projectId: 'fir-test-b43d4',
    storageBucket: 'fir-test-b43d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiExWbdXx4fE8uYrCV4STshv2Was_f2wo',
    appId: '1:1085267534409:ios:ef26dc194972f5e71b5598',
    messagingSenderId: '1085267534409',
    projectId: 'fir-test-b43d4',
    storageBucket: 'fir-test-b43d4.appspot.com',
    iosBundleId: 'com.example.masterStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiExWbdXx4fE8uYrCV4STshv2Was_f2wo',
    appId: '1:1085267534409:ios:15e0430b5129d16e1b5598',
    messagingSenderId: '1085267534409',
    projectId: 'fir-test-b43d4',
    storageBucket: 'fir-test-b43d4.appspot.com',
    iosBundleId: 'com.example.masterStore.RunnerTests',
  );
}
